project:
  type: website
  output-dir: docs
  
website:
  title: "WinBUGS"
  page-navigation: true
  page-footer: "Copyright 2023, Xin-Wei Huang"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

