project:
  type: website
  output-dir: docs

website:
  title: "A quick tutorial of WinBUGS and R2WinBUGS"
  page-navigation: true

output:
  html_document:
    toc: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    bibliography: references.bib

editor: visual

google_site_verification:  8J_S248QY53-wJumfaFWU5xEcd0WdHJmiOU2ytZSvAs
enable_google_verification: true
